#!/bin/bash -e
TRACER_DIR=$(python -c "import os.path as o, importlib.util as i; print(o.dirname(i.find_spec('bintrace').origin))")
TRACER_PATH="$TRACER_DIR/bin/qemutracer-qemu-x86_64"
PLUGIN_PATH="$TRACER_DIR/bin/libtrace.so"
exec "$TRACER_PATH" -g 3333 -d plugin,nochain -plugin "$PLUGIN_PATH",arg=$(basename $1).trace $*
